before_install:
  - sudo apt-get install libsodium
dist: xenial
language: ruby
script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:structure:load
  - bundle exec rake test
after_success:
    - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
