before_install:
  - sudo apt-get install libsodium18 libsodium-dev
dist: xenial
language: ruby
services:
  - postgresql
before_script:
  - psql -c "CREATE USER openhub_user WITH PASSWORD 'openhub_password';" -U postgres
script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:structure:load
  - bundle exec rake test
after_success:
    - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
